- .gitignore
- localhost.json.SAMPLE
- pom.xml
- src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
- src/main/java/edu/ucsb/cs56/mapache_search/SearchObject.java
- src/main/java/edu/ucsb/cs56/mapache_search/search/Item.java
- src/main/java/edu/ucsb/cs56/mapache_search/search/SearchResult.java
- src/main/resources/templates/fragments/basic_search_form.html
- src/main/resources/templates/searchResults.html
In this PR, we introduce the returning of some basic search results.
> pc - show some search results

- README.md
- src/main/java/edu/ucsb/cs56/mapache_search/GoogleSearchService.java
> Print a descriptive error when apiKey is undefined

- pom.xml
- src/main/config/heroku/heroku.properties
- src/main/config/localhost/localhost.properties
- src/main/resources/application.properties
Steps to get it running on localhost:
1. Pull these changes
2. Go to localhost.json, and delete the three lines starting with `spring.datasource`
3. Run `source env.sh`
4. Run `mvn clean`
5. Run `mvn -P localhost spring-boot:run`
6. Navigate to `localhost:8080` in your browser
> db setup H2 so we can test the app on localhost

- src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
- src/main/java/edu/ucsb/cs56/mapache_search/entities/SearchResultEntity.java
- src/main/java/edu/ucsb/cs56/mapache_search/repositories/SearchResultRepository.java
- Added search result entity and repository with URLs and vote counts
- Saved new search results into the repository
- Added "voteResults" attribute to model which stores a list of search results pulled from the database which can be used in template to display vote counts
> db/ml added search result table, insert all new results

- src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
- src/main/java/edu/ucsb/cs56/mapache_search/search/Item.java
- src/main/resources/templates/fragments/bootstrap_nav_header.html
- src/main/resources/templates/fragments/up_down_search_form.html
- src/main/resources/templates/searchUpDownResults.html
- src/main/resources/templates/upDownIndex.html
Created all the accessory links and pages needed to create a new link in the navbar where a rating section can be added when a search is done.
> 7PM UpDown Navbar Fixes

- src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
- src/main/resources/static/css/results.css
- src/main/resources/templates/fragments/bootstrap_head.html
- src/main/resources/templates/fragments/up_down_result_row.html
- src/main/resources/templates/searchUpDownResults.html
- Created a wrapper class that combines results data from the Google API and the database
- Updated the up/down search results page to the latest version from the UX team, and then added the vote count and up/down buttons to each result (links currently do not go anywhere)
> 7PMUpDown display vote totals and add buttons

- .gitignore
- src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
- src/main/java/edu/ucsb/cs56/mapache_search/search/SearchResult.java
- src/main/resources/templates/searchUpDownResults.html
We add and update an exception handler for API error.
Now, when JSON response from google search api is:{"error": "401: Unauthorized"} (Issue #27 )
The search result will not be an empty item list but an error message that lead user to user settings page and correct the API.
> My/By - API Exception Handler

- src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
- Adds a compareTo function to the Vote Result Wrapper, which provides ordering between search results
- Sorts by vote count first, then the position it came back in the Google API
> db sort results by vote first, then position

- src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
- src/main/resources/templates/fragments/basic_search_form.html
- src/main/resources/templates/searchResults.html
Fixes #39 
In this pull request in searchResults.html, we:
- commented out the "kind" table 
- added the search bar with the previous input already filled out
Lucas Nguyen (lucastnguyen) and Jennifer Lo (jenny353) worked on this PR.
> add search bar and show previous search

- src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
- src/main/java/edu/ucsb/cs56/mapache_search/VoteController.java
- src/main/java/edu/ucsb/cs56/mapache_search/entities/UserVote.java
- src/main/java/edu/ucsb/cs56/mapache_search/repositories/VoteRepository.java
- src/main/resources/templates/fragments/up_down_result_row.html
Remember users votes. Prevents users from double voting. Computes votecount based on number of upvotes minus number of downvotes.
> Ml/aq/my/db Tie users to votes

- src/main/resources/css/styles.css
- src/main/resources/templates/fragments/basic_search_form.html
- src/main/resources/templates/fragments/bootstrap_footer.html
- src/main/resources/templates/index.html
- src/main/resources/templates/searchResults.html
Fixes #62 
Restyles Search page:
- retyles the search bar
- restyles the index page
> Jl restyle search page

- .travis.yml
In this PR, we add the configuration needed for Travis CI
> pc - add .travis.yml for Travis CI

- src/main/java/edu/ucsb/cs56/mapache_search/BasicErrorController.java
- src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
- src/main/resources/templates/errors/401.html
- src/main/resources/templates/errors/404.html
- src/main/resources/templates/errors/500.html
- src/main/resources/templates/errors/error.html
- src/main/resources/templates/errors/notLoggedIn.html
Fixes #50, #95 
This PR will adds more descriptive error handling to the application.
- if the user is not logged in, it goes to a special page that tells the user to log in, and provides a home button that redirects the user to "/"
- if the user does not have a valid API key (error 401: unauthorized), it goes to a page that tells the user to enter a valid API key, and provides a settings button that redirects the user to "/user/settings"
- if the page is not found (error 404), it redirects to a page that has a button that returns the user back to "/"
- handles error 500
> ln error handling

- src/main/java/edu/ucsb/cs56/mapache_search/Application.java
- src/main/java/edu/ucsb/cs56/mapache_search/AuthControllerAdvice.java
- src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
- src/main/java/edu/ucsb/cs56/mapache_search/UserController.java
- src/main/java/edu/ucsb/cs56/mapache_search/entities/AppUser.java
- src/main/resources/application.properties
- src/main/resources/templates/fragments/basic_search_form.html
- src/main/resources/templates/searchResults.html
- src/main/resources/templates/user/settings.html
Added a counter for the number of searches each user does per day. Stores max searches allowed and number of searches today in database
> Jc counter for api

- src/main/java/edu/ucsb/cs56/mapache_search/GoogleSearchService.java
- src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
- src/main/java/edu/ucsb/cs56/mapache_search/SearchParameters.java
- src/main/java/edu/ucsb/cs56/mapache_search/SearchService.java
- src/main/java/edu/ucsb/cs56/mapache_search/search/SearchInformation.java
- src/main/java/edu/ucsb/cs56/mapache_search/search/SearchResult.java
- src/main/resources/templates/fragments/basic_search_form.html
- src/main/resources/templates/fragments/pagination.html
- src/main/resources/templates/searchResults.html
Fixes #41 
This PR adds pagination support to the results page. The search controller model and search service have been updated to support page number.
> Implement Pagination

- src/main/resources/templates/fragments/basic_search_form.html
In this pull request:
- fixed previous search input on basic_search_form
> jl-fixed previous search input

- src/main/java/edu/ucsb/cs56/mapache_search/membership/AuthControllerAdvice.java
- src/main/resources/templates/fragments/bootstrap_nav_header.html
Fixed the Null Pointer Exception and the broken avatar bugs.
Note that the way we're supporting multiple authentication types is pretty hacky and liable to break. This PR doesn't really address this, but at least the program shouldn't crash anymore.
> Fixed Google OAuth bugs

- .github/workflows/maven.yml
- .travis.yml
In this PR, we add GitHub Actions and remove Travis-CI as our CI system
> pc - switch Travis-CI to GitHub Actions

- README.md
- env.bat
> jf - Added script for WinEnv variables

- src/main/java/edu/ucsb/cs56/mapache_search/membership/AuthControllerAdvice.java
- src/test/java/edu/ucsb/cs56/mapache_search/BootstrapTestHelper.java
- src/test/java/edu/ucsb/cs56/mapache_search/HomePageTest.java
- src/test/java/edu/ucsb/cs56/mapache_search/NavigationTestHelper.java
- src/test/java/edu/ucsb/cs56/mapache_search/OAuthUtils.java
Adds homepage tests for the nav bar, title, and footer, based on code from UCSB courses search.
I'm currently working on getting a SearchResultsTest class setup. If I can't finish that on time, I'd at least like to get these tests in.
> Introduce a few more tests, all based on the homepage

- heroku.json.SAMPLE
- localhost.json.SAMPLE
- src/main/java/edu/ucsb/cs56/mapache_search/membership/AuthControllerAdvice.java
- src/main/java/edu/ucsb/cs56/mapache_search/membership/GithubOrgMembershipService.java
- src/main/resources/templates/fragments/bootstrap_nav_header.html
Not sure if every element of Google OAuth has been completely removed, but at the very least there's no longer a button to log in using Google, which should be sufficient for now
> Remove Google OAuth

- README.md
We updated google API search key set up and stack-app set up.
> QG - Updated README with info about application set up

- src/main/resources/templates/fragments/bootstrap_nav_header.html
> mlr - enabled flash messages

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/SearchController.java
- src/main/java/edu/ucsb/cs56/mapache_search/entities/UserVote.java
> mo/csil Added timestamps to votes

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/SearchController.java
- src/main/java/edu/ucsb/cs56/mapache_search/entities/AppUser.java
- src/main/java/edu/ucsb/cs56/mapache_search/entities/SearchResultEntity.java
- src/main/java/edu/ucsb/cs56/mapache_search/entities/UserVote.java
Also adds toString functions for several entities in the database
> db Add logging when votes are created or deleted

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/HomePageController.java
- src/main/java/edu/ucsb/cs56/mapache_search/controllers/SearchController.java
- src/main/java/edu/ucsb/cs56/mapache_search/repositories/VoteRepository.java
- src/main/resources/templates/index.html
Adding a homepage controller and remove the homepage mapping inside the search controller. The reason I need a separate homepage controller is so the changes I made in the homepage controller would not break the functions inside the search controller and also since we are focusing on structuring the front page, creating a different controller homepage for just the homepage itself would be nice
> tb-adding new homepage controller

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/LinkController.java
- src/main/resources/templates/fragments/result_preview.html
- src/main/resources/templates/fragments/result_row.html
Pull Request for creating LinkController.java, used to have Mapache-Search results route to /link, and to have the /link url to redirect to the actual desired url.
> W 6pm b search and link data linkcontroller

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/TagController.java
- src/main/resources/templates/fragments/bootstrap_nav_header.html
- src/main/resources/templates/tags.html
Added a blank tags page; also added tags page to the navbar under team 4.
> jz - added TagController and template for Tags page

- src/main/resources/templates/fragments/result_row.html
> jf - reduced link width of search result

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/UpvoteHistoryController.java
- src/main/java/edu/ucsb/cs56/mapache_search/repositories/VoteRepository.java
- src/main/resources/templates/fragments/upvote_sort_dropdown.html
- src/main/resources/templates/user/upvotehistory.html
This commit allows the user to view their positive upvote history in their user settings.
> Query and display user upvote history

- src/main/resources/templates/user/taghistory.html
> ns/pb - added search bar in tag history page

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/HomePageController.java
- src/main/java/edu/ucsb/cs56/mapache_search/controllers/SearchController.java
- src/main/resources/templates/fragments/bootstrap_nav_header.html
- src/main/resources/templates/index.html
- src/main/resources/templates/searchResults.html
In this pull request, I removed the team title in the top navigation bar so the top bar will not display "Team 1, Team 2, Team 3 and Team 4" anymore
> Tb w 5pm a removing team title navbar

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/TagController.java
- src/main/resources/templates/fragments/bootstrap_nav_header.html
- src/main/resources/templates/tags.html
> jf/ts - add tag search result button

- src/main/resources/static/css/results.css
> ts/jf - changed upvote cursor to pointer

- src/main/java/edu/ucsb/cs56/mapache_search/membership/GithubOrgMembershipService.java
Removed holdover code from Google OAuth and removed the check that looks for lack of email attribute to assign Google or Github OAuth as it isn't consistent.
> Consolidated Authentication code

- src/main/resources/templates/fragments/basic_search_form.html
> jf/ts/jz - changed search button font for consistency

- src/main/java/edu/ucsb/cs56/mapache_search/search/GoogleSearchService.java
This PR implements the google search API to filter by timestamp and specific site. Because #134 and #147 contain the specific features that will actually provide value to the end user, this PR only provides comments on how to easily implement those features. As of currently, the filters can only be hard coded in to see the results, as the filtered search page PR is not merged yet, so no user input can be taken.
> ck/ap - added comments as guidelines for how to implement filters

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/GithubController.java
- src/main/java/edu/ucsb/cs56/mapache_search/membership/AuthControllerAdvice.java
- src/main/java/edu/ucsb/cs56/mapache_search/membership/GithubOrgMembershipService.java
- src/main/java/edu/ucsb/cs56/mapache_search/membership/MembershipService.java
- src/main/resources/application.properties
- src/main/resources/templates/github/index.html
- src/main/resources/templates/index.html
Project repos are read from the applicaiton.properties file within GithubOrgMemberShipService. The repos are then inserted into a list, a function named getRepos returns the list . Within an index.html for the github page on mapache-search, links are created for the repos that lead to their github page under the ucsb-cs56-w20 organization.
> W 6pm project repos

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/HomePageController.java
- src/main/resources/templates/index.html
#121 Changed home page to show recently upvoted links.
> mo Front page shows recently upvoted links

- README.md
*I hid the “upvoted” links to only be viewed once the user “logged in”.
*bolded some buttons etc.. minor stuff
*created cards
*Mapache description ONLY visible prior to signing in
> W 5pm a landing page

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/HomePageController.java
- src/main/java/edu/ucsb/cs56/mapache_search/controllers/SearchController.java
- src/main/java/edu/ucsb/cs56/mapache_search/entities/SearchResultEntity.java
- src/main/java/edu/ucsb/cs56/mapache_search/repositories/SearchResultRepository.java
- src/main/resources/templates/filter.html
- src/main/resources/templates/fragments/result_row.html
- src/main/resources/templates/index.html
- src/main/resources/templates/user/upvoteascending.html
- src/main/resources/templates/user/upvotedescending.html
- src/main/resources/templates/user/upvotehistory.html
LH - display prettier links on home page
> LH - display prettier links on home page

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/SearchController.java
- src/main/java/edu/ucsb/cs56/mapache_search/entities/SearchTerms.java
- src/main/java/edu/ucsb/cs56/mapache_search/repositories/SearchTermsRepository.java
- src/test/java/edu/ucsb/cs56/mapache_search/HomePageTest.java
Generated an entity called searchTerms and a repository called searchTermsRepository that stores individual searchTerms that stores the query that the user typed in each time they search, it also stores the count of how frequently the search query has been searched as well as storing the most recent timestamp.
> Tb 5pm w a column store search query

- src/main/resources/templates/fragments/bootstrap_nav_header.html
- src/main/resources/templates/index.html
> Added link to landing page in the "Researchers" card

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/GithubController.java
- src/main/java/edu/ucsb/cs56/mapache_search/entities/GitHubTeam.java
- src/main/java/edu/ucsb/cs56/mapache_search/membership/AuthControllerAdvice.java
- src/main/java/edu/ucsb/cs56/mapache_search/membership/GithubOrgMembershipService.java
- src/main/java/edu/ucsb/cs56/mapache_search/membership/MembershipService.java
- src/main/resources/templates/github/index.html
This is a pretty good template for how to call the github API
> Added list of teams user is on to github page

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/HomePageController.java
- src/main/java/edu/ucsb/cs56/mapache_search/controllers/SearchController.java
- src/main/java/edu/ucsb/cs56/mapache_search/search/SearchParameters.java
- src/main/resources/templates/filter.html
- src/main/resources/templates/fragments/filtered_search_form.html
Added preset filter variables in searchParameters class. Modified the filter table such that user inputs get store in search Parameters.
Issue: https://github.com/ucsb-cs56-w20/mapache-search/issues/142
[ ] - created filter variables in searchParameters
[ ] - wrote setter/getter functions for those new variables
[ ] - tested that user inputs get stored in those variables (test the code by removing the commented out code in SearchController.java and find "ohdaijhdijsdisadhk, " in terminal when doing a filter search)
> W 5pm b - hx/sw/nv - implemented preset search class

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/SearchController.java
- src/main/java/edu/ucsb/cs56/mapache_search/entities/SearchQueries.java
- src/main/java/edu/ucsb/cs56/mapache_search/repositories/SearchQueriesRepository.java
- src/test/java/edu/ucsb/cs56/mapache_search/HomePageTest.java
Add a new Search Queries Table includes GitHub uid, timestamp of the search, and the id of the search term.
> LH - add a new Search Queries Table

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/TagHistoryController.java
- src/main/java/edu/ucsb/cs56/mapache_search/repositories/ResultTagRepository.java
- src/main/java/edu/ucsb/cs56/mapache_search/repositories/VoteRepository.java
- src/main/resources/templates/user/taghistory.html
Allows the user to view the tag history in the settings
> Create a table for tag history

- src/main/resources/static/js/results.js
- src/main/resources/templates/fragments/bootstrap_scripts.html
- src/main/resources/templates/searchResults.html
> jf/ts - moved upvote JavaScript into a static file

- src/test/java/edu/ucsb/cs56/mapache_search/HomePageTest.java
- src/test/java/edu/ucsb/cs56/mapache_search/LinkControllerTest.java
> jf/ts - added bean for tag repo in tests

- src/main/resources/templates/fragments/result_preview.html
> ts - restyled show more buttons

- src/main/java/edu/ucsb/cs56/mapache_search/controllers/HomePageController.java
- src/main/java/edu/ucsb/cs56/mapache_search/controllers/SearchController.java
- src/main/java/edu/ucsb/cs56/mapache_search/repositories/SearchTermsRepository.java
- src/main/resources/templates/fragments/bootstrap_nav_header.html
- src/main/resources/templates/searchStatistics.html
Following issue #199 added a search statistics page for the viewer to view the most recent searches
> tb- added search statistics page
